name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  wspresso-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2.30.1
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedEspressoAndroidTest
